input_dir: "data/3857/3857-frames"
image_file_extensions:
  - ".jpg"
output_dir: "data/3857/3857-rough-detections"
model:
  ckpt_file: "best.ckpt"
score_threshold: 0.3
show_detections: True
show_all_predictions: False
plot: True
frame_step: 10
